### PR TITLE
GitHub Actions: Try flake8 instead of pyflakes

### PR DESCRIPTION
**Pull request by cclauss**
[flake8](https://pypi.org/project/flake8) is a superset of pyflakes.  @h4l

### CODE REVIEW

**Comment by h4l** [comment]
Thanks @cclauss, this isn't my project, but I do like flake8.

**Comment by asmeurer** [comment]
I generally just use pyflakes because I don't really care about stylistic issues, although I'm surprised how few changes there are here. I'm fine either way though because I don't have plans to do much more with this project (for now at least, maybe I will implement some of the open issues if I end up using this again and I need them). 

I'm also happy to give either of you push access if you want to do any further work on this project.

**Comment by h4l** [comment]
Yep, removestar seems to be working well, so I don't plan to make regular changes.

On the subject of code style, I've found that using a code auto-formatter, such as [Black](https://github.com/psf/black), in conjunction with Flake8 to be a good way to go, as you get the benefits of consistent style without being distracted by nags about formatting. Black can increase the line count though, due to the way it wraps long/nested expressions over multiple lines.

This PR seems like a good incremental improvement to me.

**Comment by h4l** [comment]
Also, it'd probably be a good idea to put the options passed to `flake8` into a [Flake8 config file](https://flake8.pycqa.org/en/latest/user/configuration.html), so that `flake8` can be run locally without specifying all the options manually. Otherwise I expect people would end up pushing changes and having the CI job complaining about style violations.

**Pull request closed without merging**
