### PR TITLE
Move the metadata from `setup.cfg` into `PEP 621`-compliant `pyproject.toml`.

### PR DESCRIPTION
**Pull request by KOLANICH**
Unfortunately we cannot remove `setup.py` now without replacing `versioneer` with `setuptools_scm`.

### CODE REVIEW

**Comment by asmeurer** [comment]
I didn't really have any plans on doing any more development on this project. Unless someone contributes some changes to the code I don't see there being any more releases.

**Comment by KOLANICH** [comment]
Thanks for the info. Anyway, getting rid of `setup.cfg` (which currently can only be parsed properly by `setuptools` itself (because it is not a serialization format or ini dialect, but the meaning of comma, semicolon and line breaks differs for different properties, unlike that TOML is kinda a de-facto standard having multiple impls to read and write), and using the API to do that emits a warning that `setup.cfg` support will be removed from `setuptools` in future) should make the things easier for the devs of tools dealing with sdist metadata. Like my new package manager, that bypasses PyPI by fetching packages from their source repos. (the PR about project links was mainly motivated by the fact that there were no info within the metadata to determine the source code repo, now that info is present there)

**Comment by KOLANICH** [comment]
And, as I have said, I'd like to get rid of versioneer in favour of `setuptools_scm`, but it should be a part of another PR.

**Comment by Saransh-cpp** [comment]
Oops, I just saw this. Thanks for working on this, @KOLANICH! I've recently migrated `removestar`'s build-backend to `hatch` and `hatch-vcs`, getting rid of `setup.py`, `setup.cfg`, `MANIFEST.in`, `versioneer.py`, ..., and a lot of files.

So sorry for not looking at this before 🙂 

Closing this as the work is done!

**Pull request closed without merging**
